apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-app
  labels:
    app: docker-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-app
  template:
    metadata:
      labels:
        app: docker-app
    spec:
      containers:
        - name: react-app
          image: europe-north1-docker.pkg.dev/vm-test-project-437322/test-repository/docker-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
