apiVersion: apps/v1
kind: Deployment
metadata:
    name: docker-app
    labels:
        app: docker-app
spec:
    replicas: 2
    selector:
        matchLabels:
            app: docker-app
    template:
        metadata:
            labels:
                app: docker-app
        spec:
            containers:
                - name: react-app
                  image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8080
