name: Deploy Docker Container

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Connect to server and deploy Docker container
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
            # Pull the repo
            cd ~/portfolio-assignment
            git pull

            # Stop the old container, if it exists
            docker stop docker-app || true
            docker rm docker-app || true

            # Start a new container with the latest image
            cd cd ~/portfolio-assignment/docker-app
            docker build -t docker-app .
            docker run -d -p 127.0.0.1:3000:3000 docker-app
          EOF
